spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/milestone_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  profiles:
    active: default
server:
  port: 8080
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.example.project: DEBUG
